//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartFridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInFridge
    {
        public int Id { get; set; }
        public string BarcodeNumber { get; set; }
        public string Amount { get; set; }
        public string Unit { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
